Add rectangle
ManarOmari/Portoflio pull request #3
Opened 2022-05-26 13:59 UTC by ManarOmari

add rectangle and test setup html and css

2022-05-26 16:31 UTC, danmainah requested changes
Hi @ManarOmari, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Github flow was correctly used


# Required Changes ♻️

- [ ] Kindy make sure your design matches the design given, below is a comparison between your design and the given design;

Figma Design          |  Your design     
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/61408860/170532160-b7e4ea85-0a9b-4c51-bef7-d575810644aa.png) |  ![image](https://user-images.githubusercontent.com/61408860/170532211-2ee4f462-5e7e-4284-ac9a-35ee3380ceea.png)

- [ ] Kindly add the getting started section in your readme file, I can see the subtitles already added.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-05-26 16:31 UTC, danmainah commented on index.html
> +                    <img src="assets/images/toolbar-mobile.png" alt="image icon logo">
- [ ] Kindly remove the image logo from your nav tag, only the hamburger section should have a nav tag, also make sure your logo has a link `<a>` tag.

2022-05-26 16:31 UTC, danmainah commented on index.html
> +                    <img src="assets/images/toolbar-mobile.png" alt="image icon logo">
- [ ] Kindly make sure at this stage you only have a hamburger menu in your nav items, as the project is beginning with a mobile version, the other sub-menus will be implemented later.

2022-05-26 16:31 UTC, danmainah commented on index.html
>         </div>
- [ ] Kindly make sure your button, has an an`<a>` tag or a `<button>` tag and it follows the design given.

2022-05-27 05:19 UTC, merged

2022-05-27 05:38 UTC, ManarOmari commented
I closed this pull request by mistake and i cant to reopen it again

On Thu, May 26, 2022 at 7:31 PM Daniel Maina ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @ManarOmari <https://github.com/ManarOmari>,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> Highlights
>
> ✔️ No linter errors
> ✔️ Github flow was correctly used
> Required Changes ♻️
>
>    - Kindy make sure your design matches the design given, below is a
>    comparison between your design and the given design;
>
> Figma Design Your design
> [image: image]
> <https://user-images.githubusercontent.com/61408860/170532160-b7e4ea85-0a9b-4c51-bef7-d575810644aa.png> [image:
> image]
> <https://user-images.githubusercontent.com/61408860/170532211-2ee4f462-5e7e-4284-ac9a-35ee3380ceea.png>
>
>    - Kindly add the getting started section in your readme file, I can
>    see the subtitles already added.
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> _As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have
> a limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.
> ------------------------------
>
> In index.html
> <https://github.com/ManarOmari/Portoflio/pull/3#discussion_r882852783>:
>
> > @@ -16,7 +16,7 @@
>
>
>
>                 <div class="header-navbar-image">
>
>                     <div class="flex-container-img">
>
> -                    <img src="assets\images\toolbar-mobile.png">
>
> +                    <img src="assets/images/toolbar-mobile.png" alt="image icon logo">
>
>
>
>    - Kindly remove the image logo from your nav tag, only the hamburger
>    section should have a nav tag, also make sure your logo has a link <a>
>    tag.
>
> ------------------------------
>
> In index.html
> <https://github.com/ManarOmari/Portoflio/pull/3#discussion_r882856731>:
>
> > @@ -54,13 +58,13 @@ <h1>I’m Alexandra Glad to see you!</h1>
>
>         </div>
>
>
>
>    - Kindly make sure your button, has an an<a> tag or a <button> tag and
>    it follows the design given.
>
> ------------------------------
>
> In index.html
> <https://github.com/ManarOmari/Portoflio/pull/3#discussion_r882854604>:
>
> > @@ -16,7 +16,7 @@
>
>
>
>                 <div class="header-navbar-image">
>
>                     <div class="flex-container-img">
>
> -                    <img src="assets\images\toolbar-mobile.png">
>
> +                    <img src="assets/images/toolbar-mobile.png" alt="image icon logo">
>
>
>
>    - Kindly make sure at this stage you only have a hamburger menu in
>    your nav items, as the project is beginning with a mobile version, the
>    other sub-menus will be implemented later.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ManarOmari/Portoflio/pull/3#pullrequestreview-986476570>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIDTEI6Y2VUGFBXJQBEEYFLVL6ROZANCNFSM5XBIZG2A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>