Update README.md
ManarOmari/Portoflio pull request #6
Opened 2022-05-27 05:32 UTC by ManarOmari

I closed the previous pull request by mistake

2022-05-27 05:52 UTC, Ginohmk requested changes
Hi @ManarOmari , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![keep-trying-youre-almost-there](https://user-images.githubusercontent.com/67087664/169483884-c624db70-793d-42be-8ebe-afef6a1cd5c3.gif)

 ## Highlights
- Linter Passed :+1: 


 ## Required Changes ♻️
_Check the comments under the review._

Reach me on Slack  `@Kanu mike chibundu`

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-27 05:52 UTC, Ginohmk commented on README.md
> +then set background image for the content section which conains a text and images
- Please add the CSS styling to your project as it is missing that, making your project not look like the Figma design 
##### Figma design
![Screenshot from 2022-05-27 06-46-53](https://user-images.githubusercontent.com/58771507/170638044-2c16f8ae-e943-474e-b99b-a34a56e368da.png)

##### Your design
![Screenshot from 2022-05-27 06-43-19](https://user-images.githubusercontent.com/58771507/170638079-2b5d3f75-3797-4d9d-981e-f9cc7404171f.png)

**Notes:**
- Please also make sure you are done with the given sectioned task, before requesting a review
- Please also make sure you use only one branch when neccessary

If you need for explanation concerning this feedback, Feel free to reach out to me on Slack: `@Kanu mike chibundu`

2022-05-30 09:13 UTC, sja-thedude requested changes
## Required Changes ♻️

Hi @ManarOmari, This is @sja-thedude your code reviewer.

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![200w](https://user-images.githubusercontent.com/70269507/159484303-3187dacc-4a82-4263-bb1a-8d72417ce1d9.gif)

 ## Highlights
✔️ Good job so far

 ## Required Changes ♻️
- [ ] Kindly make sure to follow the loom video attached to make changes [view here](https://www.loom.com/share/15243cf596d34ed89975bb1bd3d62099).
- [ ] Optional (But highly recommended): Kindly make sure to Name your Pull request title "Portfolio: Setup" and Pull request description to "Made the first milestone for the portfolio by the building the introduction part as per the Figma design."

As suggested previously and shown in the video attached kindly:
- [ ] Add the background image correctly as per the Figma design.
- [ ] Kindly follow the spacing and font size as per the Figma design.
- [ ] Kindly display the heading with the correct font weight as per the Figma design.
- [ ] Make sure to display all the contact image icons as per the Figma design.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 14:19 UTC, ManarOmari commented
Made the first milestone for the portfolio by the building the introduction part as per the Figma design

2022-05-31 14:21 UTC, ManarOmari commented
@sja-thedude I think I fixed the errors and modified all the required issues. Please, can you let me if I should to request review ?

2022-05-31 14:38 UTC, m05e5 commented
Hi please, there are still things to improve. As mentioned by the previous reviewers, you don't have a background image and you have nav links instead of the hamburger menu for the mobile version

2022-05-31 14:47 UTC, m05e5 requested changes
Hi @ManarOmari , 

Good job so far. I really like what you did!
There are some issues that you still need to work on to go to the next project but you are almost there!
![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)


## Highlights


## Required Changes ♻️
* You really did a great job but there are some features you need to improve

**imp**
![image](https://user-images.githubusercontent.com/37901469/171201421-ba9edeb5-61fc-4523-a1aa-0cf566f62fc2.png)
- [ ] Please in place of nave links kindly display the hamburger menu
- [ ] Your text is overflowing the screen please fix that
- [ ] kindly add a background image as it is on the design
- [ ] kindly readjust your padding so it resemble the Figma design
_I'm sure you can do it just keep it up_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

_@m05e5_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-31 14:47 UTC, m05e5 commented on index.html
> +            </div>
- _[optional]_ I recommend using `<ul>` for the list of social media icons and `li` for each icon

2022-06-02 00:07 UTC, ManarOmari commented
Hello ,
I finished the project part 1 and I misunderstood what the design I will to
do , all a week i was working on desktop design like this one

On Tue, May 31, 2022 at 5:48 PM Caleb Moses ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @ManarOmari <https://github.com/ManarOmari> ,
>
> Good job so far. I really like what you did!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> [image: mario_ladders]
> <https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif>
> Highlights Required Changes ♻️
>
>    - You really did a great job but there are some features you need to
>    improve
>
> *imp*
> [image: image]
> <https://user-images.githubusercontent.com/37901469/171201421-ba9edeb5-61fc-4523-a1aa-0cf566f62fc2.png>
>
>    - Please in place of nave links kindly display the hamburger menu
>    - Your text is overflowing the screen please fix that
>    - kindly add a background image as it is on the design
>    - kindly readjust your padding so it resemble the Figma design
>    *I'm sure you can do it just keep it up*
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> ***@***.*** <https://github.com/m05e5>*
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/ManarOmari/Portoflio/pull/6#discussion_r885735643>:
>
> > -       <div class="footer-btns">
>
> -
>
> +       <div class="linkedin">
>
>          <a href="#">
>
> -        <img src="/assets/images/twitter.png" alt="twitter image" class="twitter">
>
> -         </a>
>
> -
>
> -
>
> -           <a href="#">
>
> -            <img src="/assets/images/Linkedin_icon.png" alt="linked in  image" class="linkedin">
>
> +            <img src="assets/images/Linkedin_icon.png" alt="linked in  image" class="linkedin">
>
>             </a>
>
> -
>
> -
>
> +       </div>
>
> +           <div class="meduim">
>
>              <a href="#">
>
> -                <img src="/assets/images/meduim.png" alt="meduim in  image" class="meduim">
>
> +                <img src="assets/images/meduim.png" alt="meduim in  image" class="meduim">
>
>                 </a>
>
> -
>
> -
>
> -            <a href="#">
>
> -                <img src="/assets/images/github.png" alt="github in  image" class="github">
>
> +           </div>
>
> +           <div class="github">
>
> +               <a href="#">
>
> +                <img src="assets/images/github.png" alt="github in  image" class="github">
>
>                 </a>
>
> -
>
> -
>
> +           </div>
>
> +           <div class="anglelist">
>
>              <a href="#">
>
> -                <img src="/assets/images/anglelist.png" alt="angle list in  image" class="anglelist">
>
> +                <img src="assets/images/anglelist.png" alt="angle list in  image" class="anglelist">
>
>                 </a>
>
> -
>
> -       </div>
>
> -    </div>
>
> +           </div>
>
> +            </div>
>
>
>
>    - *[optional]* I recommend using <ul> for the list of social media
>    icons and li for each icon
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ManarOmari/Portoflio/pull/6#pullrequestreview-990593484>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIDTEI6YDM74HVRKC7UTPNDVMYRCVANCNFSM5XDFLKNA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-02 00:12 UTC, ManarOmari commented
I updated the design to mobile version since I was working on desktop design all the last week . this is why i didnt go forward . @m05e5

2022-06-02 00:37 UTC, danielufeli approved these changes
Hi @ManarOmari ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️
- Good use of GitHub flow ✔️
- Clean Code ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 00:37 UTC, danielufeli commented on index.html
> +                   <a class="hamburger-menue" href="#">
- [Optional] Nicely done, kindly add a little `right-margin` to the hamburger menu so it aligns with what you have in the Figma Design

2022-06-02 06:44 UTC, merged